DROP TABLE dbo.Accounts;
DROP TABLE dbo.Categories;
DROP TABLE dbo.CategoryPriceTiers;
DROP TABLE dbo.CreditCodes;
DROP TABLE dbo.SKUCrossReferences;
DROP TABLE dbo.Customers;
DROP TABLE dbo.CustomerCreditCards;
DROP TABLE dbo.CustomerPriveLevels;
DROP TABLE dbo.CustomerShipTos;
DROP TABLE dbo.InventorySettings;
DROP TABLE dbo.Orders;
DROP TABLE dbo.OrderItems;
DROP TABLE dbo.OrderPayments;
DROP TABLE dbo.Payments;
DROP TABLE dbo.PriceTiers;
DROP TABLE dbo.SalePrices;
DROP TABLE dbo.SalesCostCodes;
DROP TABLE dbo.SKU;
DROP TABLE dbo.SKUCostQtys;
DROP TABLE dbo.SKUPrices;
DROP TABLE dbo.SKUQuantityDiscounts;
DROP TABLE dbo.SKUSerialLots;
DROP TABLE dbo.SKUVendorCosts;
DROP TABLE dbo.SubAssemblies;
DROP TABLE dbo.SystemSettings;
DROP TABLE dbo.TaxCodes;
DROP TABLE dbo.Vendors;
DROP TABLE [dbo.Zones];
CREATE TABLE dbo.Accounts (
  id                    int IDENTITY(1, 1) NOT NULL, 
  active                bit NULL, 
  username              varchar(50) NULL, 
  password              varchar(50) NULL, 
  permissionOrders      bit NULL, 
  permissionInventory   bit NULL, 
  permissionReceivables bit NULL, 
  permissionSettings    bit NULL, 
  permissionUsers       bit NULL, 
  permissionQuickbooks  bit NULL, 
  createdAt             datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy             int NULL, 
  updatedAt             datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy             int NULL);
CREATE TABLE dbo.Categories (
  id           int IDENTITY(1, 1) NOT NULL, 
  active       bit NULL, 
  categoryName varchar(50) NOT NULL, 
  calculateAs  int NOT NULL, 
  createdAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy    int NOT NULL, 
  updatedAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy    int NOT NULL);
CREATE TABLE dbo.CategoryPriceTiers (
  id          int IDENTITY(1, 1) NOT NULL, 
  active      bit NULL, 
  categoryId  int NOT NULL, 
  priceTierId int NOT NULL, 
  margin      decimal(18, 4) NULL, 
  createdAt   datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy   int NOT NULL, 
  updatedAt   datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy   int NOT NULL);
CREATE TABLE dbo.CreditCodes (
  id             int IDENTITY(1, 1) NOT NULL, 
  active         bit NULL, 
  code           varchar(3) NULL, 
  paymentAllowed varchar(50) NULL, 
  creditLimit    varchar(50) NULL, 
  createdAt      datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy      int NOT NULL, 
  updatedAt      datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy      int NOT NULL);
CREATE TABLE dbo.SKUCrossReferences (
  id             int IDENTITY(1, 1) NOT NULL, 
  active         bit NULL, 
  SkuId          int NOT NULL, 
  vendorId       int NOT NULL, 
  crossReference varchar(50) NULL, 
  createdAt      datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy      int NOT NULL, 
  updatedAt      datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy      int NOT NULL);
CREATE TABLE dbo.Customers (
  id                      int IDENTITY(1, 1) NOT NULL, 
  active                  int NULL, 
  customerNumber          varchar(3) NULL, 
  customerName            varchar(50) NULL, 
  address1                varchar(250) NULL, 
  address2                varchar(250) NULL, 
  city                    varchar(50) NULL, 
  state                   varchar(2) NULL, 
  zipcode                 varchar(10) NULL, 
  businessPhone           varchar(10) NULL, 
  businessPhoneExtension  varchar(5) NULL, 
  fax                     varchar(10) NULL, 
  homePhone               varchar(10) NULL, 
  email                   varchar(50) NULL, 
  dateOpened              date NOT NULL, 
  salesman                varchar(50) NULL, 
  resale                  bit NULL, 
  taxable                 bit NULL, 
  sendStatements          bit NULL, 
  statementCustomerNumber varchar(50) NULL, 
  statementName           varchar(50) NULL, 
  priceTierId             int NULL, 
  terms                   varchar(50) NULL, 
  limit                   varchar(50) NULL, 
  coreTracking            varchar(50) NULL, 
  coreBalance             decimal(18, 4) NULL, 
  printCoreTotal          bit NULL, 
  accountType             varchar(50) NULL, 
  poRequired              bit NULL, 
  creditCodeId            int NULL, 
  interestRate            decimal(18, 4) NULL, 
  accountBalance          decimal(16, 2) NULL, 
  yearToDatePurchases     int NULL, 
  yearToDateInterest      decimal(16, 2) NULL, 
  dateLastPurchased       date NULL, 
  memo                    varchar(max) NULL, 
  archived                bit NULL, 
  createdAt               datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy               int NOT NULL, 
  updatedAt               datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy               int NOT NULL);
CREATE TABLE dbo.CustomerCreditCards (
  id         int IDENTITY(1, 1) NOT NULL, 
  active     bit NULL, 
  customerId int NOT NULL, 
  cardNumber varchar(50) NULL, 
  cardType   varchar(50) NULL, 
  expires    date NULL, 
  priority   int NULL, 
  createdAt  datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy  int NOT NULL, 
  updatedAt  datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy  int NOT NULL);
CREATE TABLE dbo.CustomerPriveLevels (
  id            int IDENTITY(1, 1) NOT NULL, 
  active        bit NULL, 
  skuId         int NOT NULL, 
  categoryId    int NOT NULL, 
  customerId    int NOT NULL, 
  manufactuerer varchar(50) NULL, 
  commodityCode varchar(50) NULL, 
  salesCode     int NULL, 
  priceTierId   int NULL, 
  purchaseQty   int NULL, 
  adjustment    decimal(18, 4) NULL, 
  createdAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy     int NOT NULL, 
  updatedAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy     int NOT NULL);
CREATE TABLE dbo.CustomerShipTos (
  id         int IDENTITY(1, 1) NOT NULL, 
  active     bit NULL, 
  customerId int NOT NULL, 
  name       varchar(50) NULL, 
  address1   varchar(250) NULL, 
  address2   varchar(250) NULL, 
  city       varchar(50) NULL, 
  state      varchar(2) NULL, 
  zipcode    varchar(10) NULL, 
  createdAt  datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy  int NOT NULL, 
  updatedAt  datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy  int NOT NULL);
CREATE TABLE dbo.InventorySettings (
  salesCostCodeId  int NOT NULL, 
  postToJournal    bit NOT NULL, 
  costMethod       int NOT NULL, 
  skuLabelType     varchar(50) NULL, 
  yearToDate       int NOT NULL, 
  inventory        varchar(50) NULL, 
  inventoryPayable varchar(50) NULL, 
  inventoryExpense varchar(50) NULL, 
  newCoreInventory varchar(50) NULL, 
  oldcoreInventory varchar(50) NULL);
CREATE TABLE dbo.Orders (
  id                 int IDENTITY(1, 1) NOT NULL, 
  active             bit NULL, 
  customerId         int NOT NULL, 
  customerName       varchar(50) NULL, 
  creditCode         varchar(50) NULL, 
  terms              varchar(50) NULL, 
  zone               varchar(50) NULL, 
  poNumber           varchar(50) NULL, 
  shipVia            varchar(50) NULL, 
  fob                varchar(50) NULL, 
  salesman           varchar(50) NULL, 
  shipTo             varchar(50) NULL, 
  status             int NULL, 
  processedBy        varchar(8) NULL, 
  dateShipped        date NULL, 
  invoiceNumber      varchar(50) NULL, 
  invoiceDate        date NULL, 
  invoiceDesc        varchar(50) NULL, 
  lastPayment        date NULL, 
  paidDate           date NULL, 
  interestRate       decimal(18, 4) NULL, 
  interestApplied    bit NULL, 
  discountAllowed    decimal(18, 4) NULL, 
  invoiceTotal       decimal(16, 2) NULL, 
  discountableAmount decimal(16, 2) NULL, 
  totalPaid          decimal(16, 2) NULL, 
  invoiceBalance     decimal(16, 2) NULL, 
  trainingMode       bit NULL, 
  createdAt          datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy          int NOT NULL, 
  updatedAt          datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy          int NOT NULL);
CREATE TABLE dbo.OrderItems (
  id            int IDENTITY(1, 1) NOT NULL, 
  active        bit NULL, 
  orderId       int NOT NULL, 
  skuId         int NOT NULL, 
  orderItemType int NULL, 
  quantity      int NULL, 
  description   varchar(50) NULL, 
  tax           bit NULL, 
  priceTier     int NULL, 
  unitPrice     decimal(16, 2) NULL, 
  lineTotal     decimal(16, 2) NULL, 
  salesCode     varchar(50) NULL, 
  sku           varchar(50) NULL, 
  pricePaid     decimal(16, 2) NULL, 
  coreCharge    decimal(16, 2) NULL, 
  message       varchar(255) NULL, 
  createdAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy     int NOT NULL, 
  updatedAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy     int NOT NULL);
CREATE TABLE dbo.OrderPayments (
  id        int IDENTITY(1, 1) NOT NULL, 
  active    bit NULL, 
  orderId   int NOT NULL, 
  paymentId int NOT NULL, 
  createdAt datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy int NOT NULL, 
  updatedAt datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy int NOT NULL);
CREATE TABLE dbo.Payments (
  id           int IDENTITY(1, 1) NOT NULL, 
  active       bit NULL, 
  customerId   int NOT NULL, 
  creditCardId int NOT NULL, 
  checkNumber  varchar(50) NULL, 
  datePaid     date NULL, 
  amount       decimal(16, 2) NULL, 
  onAccount    bit NULL, 
  trainingMode bit NULL, 
  createdAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy    int NOT NULL, 
  updatedAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy    int NOT NULL);
CREATE TABLE dbo.PriceTiers (
  id            int IDENTITY(1, 1) NOT NULL, 
  active        bit NULL, 
  name          varchar(50) NULL, 
  profitMargin  decimal(18, 4) NULL, 
  priceTierCode varchar(50) NULL, 
  createdAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy     int NOT NULL, 
  updatedAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy     int NOT NULL);
CREATE TABLE dbo.SalePrices (
  id              int IDENTITY(1, 1) NOT NULL, 
  active          bit NULL, 
  skuId           int NOT NULL, 
  categoryId      int NOT NULL, 
  priceTierId     int NOT NULL, 
  saleTarget      int NULL, 
  manufactuerer   varchar(50) NULL, 
  commodityCode   int NULL, 
  salesCostCodeId int NULL, 
  startDate       date NULL, 
  endDate         date NULL, 
  saleType        bit NULL, 
  salePrice1      decimal(16, 2) NULL, 
  SalePrice2      decimal(18, 4) NULL, 
  createdAt       datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy       int NOT NULL, 
  updatedAt       datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy       int NOT NULL);
CREATE TABLE dbo.SalesCostCodes (
  id           int IDENTITY(1, 1) NOT NULL, 
  active       bit NULL, 
  scCode       varchar(2) NULL, 
  salesAccount varchar(50) NULL, 
  costAccount  varchar(50) NULL, 
  title        varchar(50) NULL, 
  createdAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy    int NOT NULL, 
  updatedAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy    int NOT NULL);
CREATE TABLE dbo.SKU (
  id                int IDENTITY(1, 1) NOT NULL, 
  active            bit NULL, 
  sku               varchar(15) NOT NULL, 
  category          int NOT NULL, 
  description       varchar(25) NULL, 
  measurementUnit   varchar(2) NULL, 
  weight            decimal(18, 4) NULL, 
  costCode          int NOT NULL, 
  assetAccount      int NOT NULL, 
  taxable           bit NOT NULL, 
  manageStock       bit NOT NULL, 
  allowDiscounts    bit NOT NULL, 
  lastSold          datetime NULL, 
  orderFrom         int NOT NULL, 
  manufacturer      int NULL, 
  location          varchar(10) NULL, 
  core              decimal(18, 4) NULL, 
  commodityCode     varchar(10) NULL, 
  commissionable    bit NOT NULL, 
  quantity          int NOT NULL, 
  qtyAllocated      int NOT NULL, 
  qtyAvailable      int NOT NULL, 
  qtyCritical       int NOT NULL, 
  qtyReorder        int NOT NULL, 
  soldMonthToDate   int NOT NULL, 
  soldYearToDate    int NOT NULL, 
  coreCost          decimal(16, 2) NOT NULL, 
  inventoryValue    decimal(16, 2) NOT NULL, 
  freezePrices      bit NOT NULL, 
  memo              varchar(max) NULL, 
  subassemblyStatus bit NOT NULL, 
  subassemblyPrint  bit NOT NULL, 
  archived          bit NULL, 
  createdAt         datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy         int NOT NULL, 
  updatedAt         datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy         int NOT NULL);
CREATE TABLE dbo.SKUCostQtys (
  id        int IDENTITY(1, 1) NOT NULL, 
  active    bit NULL, 
  skuId     int NOT NULL, 
  costDate  date NULL, 
  method    varchar(50) NULL, 
  qty       int NULL, 
  cost      decimal(16, 2) NULL, 
  core      decimal(16, 2) NULL, 
  createdAt datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy int NOT NULL, 
  updatedAt datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy int NOT NULL);
CREATE TABLE dbo.SKUPrices (
  id          int IDENTITY(1, 1) NOT NULL, 
  active      bit NULL, 
  skuId       int NOT NULL, 
  priceTierId int NOT NULL, 
  price       decimal(16, 2) NULL, 
  createdAt   datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy   int NOT NULL, 
  updatedAt   datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy   int NOT NULL);
CREATE TABLE dbo.SKUQuantityDiscounts (
  id           int IDENTITY(1, 1) NOT NULL, 
  active       bit NULL, 
  skuId        int NOT NULL, 
  fromQty      int NULL, 
  toQty        int NULL, 
  priceTier    int NULL, 
  discountType int NULL, 
  discount0    decimal(16, 2) NULL, 
  discount1    decimal(18, 4) NULL, 
  createdAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy    int NOT NULL, 
  updatedAt    datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy    int NOT NULL);
CREATE TABLE dbo.SKUSerialLots (
  id            int IDENTITY(1, 1) NOT NULL, 
  active        bit NULL, 
  skuId         int NOT NULL, 
  serialNumber  varchar(50) NULL, 
  lotNumber     varchar(50) NULL, 
  dateReceived  date NULL, 
  cost          decimal(16, 2) NULL, 
  invoiceId     varchar(50) NULL, 
  purchasedFrom varchar(50) NULL, 
  createdAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy     int NOT NULL, 
  updatedAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy     int NOT NULL);
CREATE TABLE dbo.SKUVendorCosts (
  id              int IDENTITY(1, 1) NOT NULL, 
  active          bit NULL, 
  skuId           int NOT NULL, 
  vendorId        int NOT NULL, 
  vendor          varchar(50) NULL, 
  manufacturer    varchar(50) NULL, 
  memo            varchar(255) NULL, 
  packageQuantity int NULL, 
  cost            decimal(16, 2) NULL, 
  core            decimal(16, 2) NULL, 
  createdAt       datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy       int NOT NULL, 
  updatedAt       datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy       int NOT NULL);
CREATE TABLE dbo.SubAssemblies (
  id               int IDENTITY(1, 1) NOT NULL, 
  active           bit NULL, 
  targetSkuId      int NOT NULL, 
  subAssemblySkuId int NOT NULL, 
  categoryId       int NOT NULL, 
  status           bit NULL, 
  invoicePrint     bit NULL, 
  description      varchar(50) NULL, 
  quantity         int NULL, 
  createdAt        datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy        int NOT NULL, 
  updatedAt        datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy        int NOT NULL);
CREATE TABLE dbo.SystemSettings (
  taxCodeId        int NOT NULL, 
  companyName      varchar(50) NULL, 
  address1         varchar(50) NULL, 
  address2         varchar(50) NULL, 
  city             varchar(50) NULL, 
  state            varchar(50) NULL, 
  zipcode          varchar(50) NULL, 
  phone            varchar(50) NULL, 
  fax              varchar(50) NULL, 
  federalTaxNumber varchar(50) NULL, 
  trainingMode     bit NOT NULL, 
  targetPrinter    varchar(50) NULL);
CREATE TABLE dbo.TaxCodes (
  id             int IDENTITY(1, 1) NOT NULL, 
  active         bit NULL, 
  name           varchar(50) NULL, 
  classification varchar(50) NULL, 
  rate           decimal(18, 4) NULL, 
  createdAt      datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy      int NOT NULL, 
  updatedAt      datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy      int NOT NULL);
CREATE TABLE dbo.Vendors (
  id            int IDENTITY(1, 1) NOT NULL, 
  active        bit NULL, 
  archived      bit NULL, 
  vendorName    varchar(50) NULL, 
  address1      varchar(250) NULL, 
  address2      varchar(250) NULL, 
  city          varchar(50) NULL, 
  state         varchar(2552) NULL, 
  zipcode       varchar(10) NULL, 
  businessPhone varchar(10) NULL, 
  fax           varchar(10) NULL, 
  createdAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  createdBy     int NOT NULL, 
  updatedAt     datetime DEFAULT CURRENT_TIMESTAMP NULL, 
  updatedBy     int NOT NULL);
CREATE TABLE [dbo.Zones] (
  id int IDENTITY(1, 1) NOT NULL);
